version: '3.8'
services:
log-analyzer:
build: ./log-analyzer
container_name: log-analyzer
ports:
- "3000:3000"
environment:
- NODE_ENV=production
depends_on:
- log-generator
log-generator:
  build: ./log-generator
  container_name: log-generator
  environment:
    - LOG_RATE=700
frontend:
  image: nginx:stable-alpine
  container_name: realtime-frontend
  volumes:
    - ./frontend:/usr/share/nginx/html:ro
  ports:
    - "8080:80"
  depends_on:
    - log-analyzer